package com.agentstate.guard.qr

import com.agentstate.guard.network.QrPayload

/**
 * Pairing-realism boundary: the exact agentstate:// URI generated by
 * DeviceLinkClientTest from a lifecycle-consistent invitation is encoded
 * to a real bitmap, decoded by the production engine, and parsed. This is
 * the "tap scan on a real phone" contract — downstream, only beginScanPairing
 * consumes what survives this boundary.
 */
class QrPayloadRealDecoderTest {

    private val now = 1_900_000_000L

    @org.junit.Test
    fun `pair-shaped payload survives the real decoder round trip`() {
        val frame = QrFixture.render("valid_invitation")
        val scanner = QrScanner(ZxingQrDecodeEngine()) { now }
        val outcome = scanner.scanGrid(frame.grid) as QrScanner.Outcome.Found

        val parsed = QrPayload.parse(outcome.payloadText, now)
        org.junit.Assert.assertNotNull(parsed)
        org.junit.Assert.assertEquals("desktop-test01", parsed!!.desktopUuid)
        org.junit.Assert.assertEquals(1, parsed.protocolVersion)
        org.junit.Assert.assertEquals(8788, parsed.endpoint.port)
    }
}
