package com.agentstate.guard.qr

import com.agentstate.guard.network.QrPayload
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Scanner boundary contract against real encoded QR matrices:
 *
 *  - Committed fixture matrices (independently generated by PIL/qrcode) are
 *    rendered to luminance grids and decoded by the production ZXing engine.
 *    When the optional subprocess-engine hook (ASG_TEST_QR_ENGINE_COMMAND,
 *    scripts/test_qr_engine.py) is set, the same matrices additionally pass
 *    through that decoder — the contract must hold on every engine.
 *  - Every valid invitation must decode to (and only to) Found(rawText);
 *    every malformed, expired, non-QR, or foreign-QR input must fail closed
 *    as Invalid(PAIR_QR_INVALID) or null (nothing surfaced to pairing).
 *  - The pairing parser is re-asserted at the raw-text boundary so a real
 *    camera text can never reach pairing unless the full contract holds.
 */
class QrScannerTest {

    private val now = 1_900_000_000L

    private fun scanners(): List<Pair<String, QrScanner>> = buildList {
        add("zxing" to QrScanner(ZxingQrDecodeEngine()) { now })
        val command = System.getenv("ASG_TEST_QR_ENGINE_COMMAND")
        if (command != null) add("subprocess" to QrScanner(SubprocessQrDecodeEngine(command)) { now })
    }

    @Test
    fun `valid invitation decodes to Found with the verbatim payload text`() {
        val frame = QrFixture.render("valid_invitation")
        for ((name, scanner) in scanners()) {
            val outcome = scanner.scanGrid(frame.grid)
            assertTrue("$name must find the invitation", outcome is QrScanner.Outcome.Found)
            assertEquals(frame.payloadText, (outcome as QrScanner.Outcome.Found).payloadText)
            // The full parser contract holds for the decoded text.
            val parsed = QrPayload.parse(outcome.payloadText, now)
            assertNotNull(parsed)
            assertEquals("desktop-test01", parsed!!.desktopUuid)
            assertEquals("192.168.1.5", parsed.endpoint.host)
        }
    }

    @Test
    fun `valid invitation is emitted only once while it remains in the camera`() {
        val frame = QrFixture.render("valid_invitation")
        for ((name, scanner) in scanners()) {
            val first = scanner.scanGrid(frame.grid)
            val repeated = scanner.scanGrid(frame.grid)

            assertTrue("$name must emit the first valid frame", first is QrScanner.Outcome.Found)
            assertNull("$name must not start pairing again for the same visible QR", repeated)
        }
    }

    @Test
    fun `blank and dark frames yield no outcome on every engine`() {
        for ((name, scanner) in scanners()) {
            assertNull("$name must stay silent on a blank frame", scanner.scanGrid(QrFixture.blank()))
            assertNull("$name must stay silent on a dark frame", scanner.scanGrid(QrFixture.dark()))
        }
    }

    @Test
    fun `foreign QR content never reaches pairing`() {
        for (name in listOf("foreign_https", "foreign_wifi", "foreign_otpauth")) {
            val frame = QrFixture.render(name)
            for ((engine, scanner) in scanners()) {
                val outcome = scanner.scanGrid(frame.grid)
                assertTrue(
                    "$engine must fail closed for $name but was $outcome",
                    outcome is QrScanner.Outcome.Invalid &&
                        outcome.reasonCode == "PAIR_QR_INVALID",
                )
                // The decoded text itself is rejected by the parser, too.
                assertNull(QrPayload.parse(frame.payloadText, now))
            }
        }
    }

    @Test
    fun `tampered invitation fields fail closed from a real QR matrix`() {
        for (name in listOf(
            "tampered_port",
            "tampered_uuid",
            "tampered_version",
            "tampered_sign_fp",
            "truncated",
        )) {
            val frame = QrFixture.render(name)
            for ((engine, scanner) in scanners()) {
                val outcome = scanner.scanGrid(frame.grid)
                assertTrue(
                    "$engine must fail closed for $name but was $outcome",
                    outcome is QrScanner.Outcome.Invalid &&
                        outcome.reasonCode == "PAIR_QR_INVALID",
                )
                assertNull(QrPayload.parse(frame.payloadText, now))
            }
        }
    }

    @Test
    fun `expired invitation from a real QR matrix is rejected before pairing`() {
        val frame = QrFixture.render("expired_invitation")
        val scanner = QrScanner(ZxingQrDecodeEngine()) { now }
        val outcome = scanner.scanGrid(frame.grid)
        assertTrue(outcome is QrScanner.Outcome.Invalid)
        assertNull(QrPayload.parse(frame.payloadText, now))
    }

    @Test
    fun `random noise cannot crash the scanner or surface a payload`() {
        val samples = ByteArray(240 * 240).also { java.util.Random(42).nextBytes(it) }
        val noise = QrPixelGrid(240, 240, samples)
        for ((name, scanner) in scanners()) {
            assertNull("$name must fail closed on noise", scanner.scanGrid(noise))
        }
    }

    @Test
    fun `grid contract rejects malformed sample buffers at construction`() {
        var threw = false
        try {
            QrPixelGrid(29, 29, ByteArray(29 * 29 + 1))
        } catch (expected: IllegalArgumentException) {
            threw = true
        }
        assertTrue("dimension/sample-count mismatch must be rejected", threw)
    }
}
