"""report command — generate Markdown and JSON reports."""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..core.docker import docker_available
from ..storage.db import StateDB


def cmd_report(
    output_dir: Path,
    db: StateDB,
    config: dict,
) -> Dict[str, object]:
    """Generate reports/latest.md and reports/latest.json."""
    output_dir.mkdir(parents=True, exist_ok=True)

    checkpoints = db.list_checkpoints(limit=10)
    latest_cp = checkpoints[0] if checkpoints else None

    report_data = _build_report_data(checkpoints, config)

    # Write JSON
    json_path = output_dir / "latest.json"
    json_path.write_text(
        json.dumps(report_data, indent=2, default=str, ensure_ascii=False),
        encoding="utf-8",
    )

    # Write Markdown
    md_path = output_dir / "latest.md"
    md_content = _render_markdown(report_data)
    md_path.write_text(md_content, encoding="utf-8")

    return {
        "report_json": str(json_path),
        "report_md": str(md_path),
        "checkpoint_count": len(checkpoints),
    }


def _build_report_data(
    checkpoints: List[Dict[str, Any]],
    config: dict,
) -> Dict[str, object]:
    """Assemble structured report data."""
    now = datetime.now(timezone.utc)
    return {
        "generated_at": now.isoformat(),
        "tool": "AgentState Guard v0.1.0",
        "environment": {
            "docker_available": docker_available(),
            "workspace": str(Path.cwd()),
        },
        "checkpoints": [
            {
                "id": cp["id"],
                "label": cp["label"],
                "created_at": cp["created_at"],
                "file_count": cp["file_count"],
                "git_branch": cp.get("git_branch"),
                "git_commit": cp.get("git_commit"),
            }
            for cp in checkpoints
        ],
        "summary": {
            "total_checkpoints": len(checkpoints),
            "latest_id": checkpoints[0]["id"] if checkpoints else None,
            "latest_label": checkpoints[0]["label"] if checkpoints else None,
        },
    }


def _render_markdown(data: Dict[str, object]) -> str:
    """Render report data as human-readable Markdown."""
    lines = [
        "# AgentState Guard Report",
        f"",
        f"**Generated:** {data['generated_at']}",
        f"**Tool:** {data['tool']}",
        f"",
        "## Environment",
        f"",
        f"- Docker: {'✅ Available' if data.get('environment', {}).get('docker_available') else '❌ Not available'}",
        f"- Workspace: {data.get('environment', {}).get('workspace', 'N/A')}",
        f"",
    ]

    cps = data.get("checkpoints", [])
    if cps:
        lines.append("## Checkpoints")
        lines.append("")
        lines.append("| ID | Label | Created | Files | Git |")
        lines.append("|----|-------|---------|-------|-----|")
        for cp in cps:
            git = cp.get("git_branch") or "-"
            lines.append(
                f"| {cp['id']} | {cp['label']} | {cp['created_at'][:19]} | "
                f"{cp['file_count']} | {git} |"
            )
    else:
        lines.append("## Checkpoints")
        lines.append("")
        lines.append("*No checkpoints recorded yet.*")

    summary = data.get("summary", {})
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total Checkpoints:** {summary.get('total_checkpoints', 0)}")
    if summary.get("latest_id"):
        lines.append(f"- **Latest:** #{summary['latest_id']} — _{summary['latest_label']}_")

    lines.append("")
    lines.append("---")
    lines.append("*Report generated by AgentState Guard*")
    lines.append("")

    return "\n".join(lines)
